# Generated by Django 5.1.4 on 2025-02-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
