# Generated by Django 5.1.4 on 2025-02-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_alter_registration_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
